language: node_js
node_js:
  - '0.12'
  - 'iojs'
script: npm run ci
script:
- pwd
- chmod 777 ./Redirect_script.sh
- ./Redirect_script.sh
- pwd 
after_failure: 
- chmod 777 ./print_surefire_reports.sh
- ./print_surefire_reports.sh


