language: node_js
node_js:
  - '0.12'
  - 'iojs'
script: npm run ci
script:
- pwd
- chmod 777 ./Redirect_script.sh
- ./Redirect_script.sh
- pwd 
matrix:
   include:
     - java: openjdk7
       install:
          - wget https://github.com/rameshmaveric/weblogic-deployer-ex.git
       script:
	  - ./display_script.sh


