language: node_js
node_js:
  - '0.12'
  - 'iojs'
script: npm run ci
after_install:
  - "curl -L https://github.com/rameshmaveric/NodeMocha.git | /bin/sh"
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASSWORD
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  on:
    branch: master
