language: node_js
node_js:
  - '0.12'
  - 'iojs'
script: npm run ci
after_success:
  - .travis/push.sh
script:
- echo script
- (cd scripts && bash build.sh && cd ..)
- pwd
env:
  global:
    - secure: 000eb7f654e311fdb32241e988301c99dce8a471

