language: node_js
node_js:
  - '0.12'
  - 'iojs'
script: npm run ci
after_success:
  - .travis/push.sh
script:
- pwd
- cd https://github.com/rameshmaveric/webappDepolyment.git
- pwd
manifest: manifest.yml
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
    repo: rameshmaveric/webappDepolyment

